"""pl-scribble — embed the Scribble annotation tool in a PrairieLearn question.

The annotatable content is THIS element's own children (encapsulation: Scribble never
traverses PL's surrounding DOM). render() emits it as a hidden .pl-scribble-source inside
our .pl-scribble-wrap; embed.js clones it from frameElement.parentElement (our own output).

Persistence: the student's annotations are serialized (base64 of save_json()) into a hidden
<input> inside our wrapper — which sits in PL's <form> — so PrairieLearn saves them on Save /
Save & Grade like any answer. parse() validates the round-tripped blob; the submission panel
re-renders it read-only (window.__SCRIBBLE_READONLY).

Why a srcdoc iframe (not <iframe src=...>): PrairieLearn stamps
`Content-Security-Policy: frame-ancestors 'none'` + `X-Frame-Options: DENY` on every text/html
response, which blocks framing a served index.html — even same-origin. A `srcdoc` iframe is
generated by the parent document (no PL HTTP response carries those headers), so the framing
block never applies. A non-sandboxed srcdoc iframe is same-origin with the parent, and a
`<base href>` makes every relative asset URL resolve to clientFilesCourse/scribble/.

Deploy the COMPILED Scribble bundle to [course]/clientFilesCourse/scribble/ (see prairielearn/deploy.sh).
"""

import base64
import html as _html
import json
import os
import re

import lxml.html
import prairielearn as pl

ANSWERS_NAME_DEFAULT = "scribble"
# The Rust core caps decoded JSON at 30MB, but json.loads() materializes the whole tree in the SHARED
# PrairieLearn worker before we can inspect it. Cap the decoded blob below the Rust ceiling (Rust allows up to
# ~500 clippings × 2MB base64 each) so several full-size clippings fit, while the structural walk below bounds
# a pathological flat array's peak memory independently.
MAX_ANNOTATION_BYTES = 16 * 1024 * 1024  # effective decoded cap for a stored annotation blob
MAX_B64 = (MAX_ANNOTATION_BYTES + 2) // 3 * 4 + 16  # base64-inflated pre-filter on the raw input
MAX_JSON_NODES = 500_000  # structural bound (deep/wide objects); scalar coord tuples are cheap (see below)
MAX_JSON_DEPTH = 64


def _reject_constant(_tok):
    # json's Infinity/-Infinity/NaN literals are not valid Scribble data and round-trip into the stored
    # blob, where the client JSON.parse then throws → the whole submission renders empty. Reject them.
    raise ValueError("non-finite literal")


def _within_structural_bounds(obj):
    """Iterative (non-recursive) node-count + depth walk; raises ValueError if the tree is too big/deep.

    A small scalar list (a [x,y] point, a [x,y,x,y] rect) counts as ONE node — descending into it and counting
    each coordinate would exhaust the cap on normal dense handwriting (a stroke's points array). Nested stroke
    data (an array OF pairs) still descends normally, and a huge FLAT scalar array is still fully counted so it
    can't amplify memory.
    """
    stack = [(obj, 0)]
    n = 0
    while stack:
        cur, depth = stack.pop()
        n += 1
        if n > MAX_JSON_NODES or depth > MAX_JSON_DEPTH:
            raise ValueError("too complex")
        if isinstance(cur, dict):
            for v in cur.values():
                stack.append((v, depth + 1))
        elif isinstance(cur, list):
            has_container = False
            for v in cur:
                if isinstance(v, (dict, list)):
                    has_container = True
                    stack.append((v, depth + 1))
            if not has_container and len(cur) > 8:
                n += len(cur)  # a large flat scalar array is bounded; a coord tuple (<=8) is free
                if n > MAX_JSON_NODES:
                    raise ValueError("too complex")
    # v189: no return — the sole caller invokes this purely for the raise-on-oversize side effect (it does not
    # transform obj), so a `return obj` implied a value-producing contract nothing uses.

_MISSING_BUNDLE = (
    '<div style="padding:12px;border:1px solid #f0d9a8;background:#fff7e6;border-radius:8px;">'
    "<strong>pl-scribble:</strong> the Scribble bundle was not found at "
    "<code>clientFilesCourse/scribble/index.html</code>. Build it and run "
    "<code>prairielearn/deploy.sh</code>.</div>"
)
_INJECT_FAIL = (
    '<div style="padding:12px;border:1px solid #f0d9a8;background:#fff7e6;border-radius:8px;">'
    "<strong>pl-scribble:</strong> could not inject the asset base — no &lt;head&gt; found in "
    "the Scribble bundle. The bundle may be malformed.</div>"
)
_FRAME = (
    '<iframe class="pl-scribble-frame" title="%s" '
    'style="width:100%%;height:660px;border:1px solid #d7dbe0;border-radius:10px;display:block;" '
    'srcdoc="%s"></iframe>'
)
# Option C (overlay): the question prose renders VISIBLY in .pl-scribble-host and a TRANSPARENT
# Scribble iframe is laid over it so the student draws on the LIVE question rather than a clone.
# width:100% fills the host; HEIGHT is set by _OVERLAY_SIZER (an iframe is a REPLACED element —
# absolute inset:0 does NOT stretch it, so we size it in JS (v179: to the WHOLE question panel — wrap top to
# .card-body bottom, so it also covers a graded sibling input below <pl-scribble>, not just the prose). The page
# coords are locked to HTML_BASE_W=816 inside Scribble so the fixed-width replay in hydrateAnnotations stays
# faithful; min-height (== Scribble's 200px page floor) keeps a short question from clipping the canvas.
_OVERLAY_FRAME = (
    '<iframe class="pl-scribble-overlay-frame" title="%s" '
    # z-index near INT_MAX so Scribble's toolbar/notes sit ABOVE any other page overlay or browser
    # extension the student runs. It stays a good citizen: pointer-events:none (below) makes the whole
    # transparent frame click-through until "Annotate" is pressed, so other overlays remain reachable.
    'style="position:absolute;top:0;left:0;width:100%%;height:200px;border:0;background:transparent;'
    'z-index:2147482000;" '
    'srcdoc="%s"></iframe>'
)
# "Annotate" launch button (editable overlay only). Until clicked, the drawing layer passes pointer
# events THROUGH to the live question and Scribble's UI stays hidden (style.css :not(.annotate-active));
# clicking flips drawing on. Prof. Lumetta asked for an explicit launch affordance (cf. PL's Calculator).
_ANNOTATE_BTN = (
    '<button type="button" class="pl-scribble-annotate-btn" data-scribble-id="%s" aria-pressed="false" '
    # z-index above the overlay frame (2147482000) so the launch affordance is never buried by another
    # extension's overlay; the active "Done" state floats even higher (2147483000, in the sizer).
    # v177 (user): the launcher is ALWAYS on screen — position:fixed to the viewport, never scrolled away
    # with the card. The sizer places it (top-left of the visible card by default; where Done last stood
    # after an annotate session). Server-side it starts hidden-ish at the viewport top-left; the sizer's
    # first m() run positions it properly before first interaction matters.
    'style="position:fixed;top:8px;left:8px;z-index:2147482500;display:inline-flex;align-items:center;gap:6px;'
    'padding:6px 12px;border:1px solid #c9d6f7;border-radius:8px;background:#fff;color:#2f5fde;'
    'font:600 13px/1 system-ui,-apple-system,sans-serif;cursor:pointer;box-shadow:0 1px 3px rgba(20,24,28,.12);">'
    '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" '
    'stroke-linecap="round" stroke-linejoin="round"><path d="M12 20h9"/>'
    '<path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"/></svg><span>Annotate</span></button>'
)
# Size the overlay iframe to the live prose host (in sync on load / MathJax / resize), and wire the
# Annotate toggle. A custom element may emit a parent-page inline <script>; PL's page CSP has no
# script-src. The iframe is same-origin (srcdoc + allow-same-origin), so we flip a class on its body.
_OVERLAY_SIZER = (
    "<script>(function(){var w=document.currentScript.parentElement,"
    "h=w.querySelector('.pl-scribble-host'),f=w.querySelector('.pl-scribble-overlay-frame'),"
    "b=w.querySelector('.pl-scribble-annotate-btn');"
    # v179 item 3: size the overlay iframe ELEMENT to the WHOLE question panel (wrap top → .card-body bottom),
    # not just the prose host — so a graded input authored as a SIBLING below <pl-scribble> is covered and
    # drawable (annotate) / answerable (paused). The iframe is position:absolute (out of flow), so extending
    # it never pushes content; the .card-body bottom stops short of PL's Save/Grade footer, which stays
    # clickable. app.js's embed.js measures the identical span for the drawable canvas.
    "var pnl=w.closest('.card-body')||w.parentElement||h;"
    "function cover(){try{return Math.max(h.offsetHeight,Math.round(pnl.getBoundingClientRect().bottom-w.getBoundingClientRect().top),200);}catch(_){return Math.max(h.offsetHeight,200);}}"
    "function s(){f.style.height=cover()+'px';"
    # v177 A2: a viewport-FIXED pill must never strand off-screen when the window shrinks — re-clamp on
    # every resize (s already runs on resize). Applies whenever the button is body-parented (pill or FAB).
    "try{if(b&&b.parentNode===document.body&&b.style.position==='fixed'){"
    "var bx=Math.max(8,Math.min(window.innerWidth-120,parseFloat(b.style.left)||8));"
    "var by=Math.max(8,Math.min(window.innerHeight-48,parseFloat(b.style.top)||8));"
    "b.style.left=bx+'px';b.style.top=by+'px';}}catch(_){}}s();"
    "window.addEventListener('load',s);window.addEventListener('resize',s);"
    "if(window.MathJax&&MathJax.startup&&MathJax.startup.promise){MathJax.startup.promise.then(s);}"
    # v179 item 3 (Mechanism B fix): the sizer had NO ResizeObserver, so any panel growth other than
    # window-resize/first-MathJax (async input enhancement, a late image, a second typeset) grew the drawable
    # canvas but NOT the iframe element, clipping the grown bottom. Observe the panel (the iframe is absolute,
    # so re-sizing it can't feed back → no RO loop). rAF-coalesced.
    "try{if(window.ResizeObserver){var srf=0;var sro=new ResizeObserver(function(){if(srf)return;srf=requestAnimationFrame(function(){srf=0;s();});});sro.observe(pnl);if(pnl!==h)sro.observe(h);"
    # v179 review F3 (CLAUDE.md §11 rule 4): this parent-realm RO ships its teardown in the same change —
    # disconnect on the parent frame's pagehide so an in-place panel swap can't leave it firing at a detached
    # iframe (harmless writes, but a retained closure). A full-page Save&Grade GC's the realm anyway.
    "window.addEventListener('pagehide',function(){try{sro.disconnect();if(srf)cancelAnimationFrame(srf);}catch(_){}}, {once:true});}}catch(_){}"
    "f.style.pointerEvents='none';"  # default click-through — also covers the read-only view (no button)
    # v177 A1 (review blocker): the first m() runs at parse with the server-rendered FIXED button already
    # laid out, so a naive rect capture "remembers" the placeholder (8,8) and the card default became dead
    # code. Continuity is honored ONLY after a real annotate session (sbP flag, set on the ON branch).
    # V177-3: a re-rendered panel leaves the previous button as a body-level zombie — dedupe by identity.
    "if(b){var on=false,dg=null,sc=false;"
    "try{var sid=b.getAttribute('data-scribble-id');if(sid){document.querySelectorAll('.pl-scribble-annotate-btn[data-scribble-id=\"'+sid+'\"]').forEach(function(o){if(o!==b)o.remove();});}}catch(_){}"
    "function m(){f.style.pointerEvents=on?'auto':'none';"
    "var sp=b.querySelector('span'),ic=b.querySelector('svg');"
    # ACTIVE: a big, filled, DRAGGABLE floating action button, opening below the toolbar's right end. CRITICAL: a PrairieLearn
    # ancestor (question card) can carry a CSS transform, which makes a position:fixed DESCENDANT resolve
    # against THAT box, not the viewport — so the button lands off-screen down a long question and the student
    # can't find "Done". Reparent it to <body> (outside any transformed ancestor) so fixed == viewport, and
    # make it large/prominent. INACTIVE: the compact launch pill back at the question's top-right corner.
    # v172 OWNERSHIP RULE (reparent readiness plan §3): when app.js has reparented the toolbar into this page
    # (feature-detect its host, which cannot exist before app.js creates it), the ACTIVE button is WELDED into
    # the toolbar's right end BY APP.JS — this script must then skip its own fixed positioning entirely (two
    # writers fighting over one node was the collision class the plan forbids). This script still owns the
    # button's lifecycle: creation, the toggle click, the label swap, and the INACTIVE corner pill.
    "if(on){b.dataset.sbP='1';var ch=document.querySelector('.pl-scribble-chrome-host');"
    "if(!ch){if(b.parentNode!==document.body)document.body.appendChild(b);"
    # (No reparented toolbar — legacy FAB path.) Open BELOW the toolbar's RIGHT end: measure the overlay frame
    # (the question CARD) and pin Done just under the ~56px toolbar, right-aligned to the CARD — NOT the
    # viewport right, which sits out in the instructor-preview sidebar. Still fully draggable from there.
    "var fr=f.getBoundingClientRect();"
    "b.style.position='fixed';b.style.left='auto';b.style.bottom='auto';"
    "b.style.top=Math.max(4,Math.round(fr.top)+60)+'px';b.style.right=Math.max(4,Math.round(window.innerWidth-fr.right)+8)+'px';b.style.zIndex='2147483000';"
    # Same COMPACT pill as the inactive "Annotate" state (user pref: Done should look like Annotate, not a big
    # blue FAB) — only the label and the move cursor differ, since the active button is draggable.
    "b.style.padding='6px 12px';b.style.fontSize='13px';b.style.fontWeight='600';"
    "b.style.background='#fff';b.style.color='#2f5fde';b.style.borderColor='#c9d6f7';b.style.borderRadius='8px';"
    "b.style.boxShadow='0 1px 3px rgba(20,24,28,.12)';b.style.cursor='move';b.style.touchAction='none';}"
    # v184 #3b: the active button is an ✕ (close) icon, NOT the word "Done" — "Done" read like exam-submit; an
    # X reads as "close the drawing tools". Static path (no user content). Restored to the pencil on the OFF branch.
    "if(sp)sp.textContent='';if(ic)ic.innerHTML='<path d=\"M6 6l12 12M18 6L6 18\"/>';b.setAttribute('aria-label','Close drawing tools');}"
    # v177: capture where the button IS (welded in the bar, or the FAB) BEFORE unwelding — the inactive pill
    # re-appears at that exact spot ("appears the exact place you click Done"), clamped on-screen; a fresh
    # load (rect 0x0 / never annotated) defaults to the TOP-LEFT of the visible card. position:fixed keeps it
    # on the viewport permanently — the old absolute corner pill scrolled away with a long question.
    "else{var pr=null;try{if(b.dataset.sbP){var r0=b.getBoundingClientRect();if(r0&&r0.width)pr=r0;}}catch(_){ }"
    "if(b.parentNode!==document.body)document.body.appendChild(b);"
    "var fr2=f.getBoundingClientRect();"
    "var px=pr?pr.left:Math.max(8,Math.round(fr2.left)+24);"
    "var py=pr?pr.top:Math.max(8,Math.round(fr2.top)+8);"
    "px=Math.max(8,Math.min(window.innerWidth-120,Math.round(px)));"
    "py=Math.max(8,Math.min(window.innerHeight-48,Math.round(py)));"
    "b.style.position='fixed';b.style.left=px+'px';b.style.top=py+'px';b.style.bottom='auto';b.style.right='auto';b.style.zIndex='2147482500';b.style.margin='0';"
    "b.style.padding='6px 12px';b.style.fontSize='13px';b.style.fontWeight='600';"
    "b.style.background='#fff';b.style.color='#2f5fde';b.style.borderColor='#c9d6f7';b.style.borderRadius='8px';"
    "b.style.boxShadow='0 1px 3px rgba(20,24,28,.12)';b.style.cursor='pointer';"
    "if(sp)sp.textContent='Annotate';if(ic)ic.innerHTML='<path d=\"M12 20h9\"/><path d=\"M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z\"/>';b.setAttribute('aria-label','Annotate');}"
    "w.classList.toggle('scribble-active',on);b.setAttribute('aria-pressed',String(on));"
    "try{var d=f.contentDocument;if(d&&d.body)d.body.classList.toggle('annotate-active',on);}catch(e){}}"
    # Drag the active Done button to reposition it (viewport-clamped). DRAG_SLOP separates a drag from a click,
    # and sc suppresses the toggle on the click that ends a drag; sc resets on every pointerdown so it can't stick.
    # v179 item 1: the INACTIVE launcher is now DRAGGABLE (like the toolbar), and where it is dropped is where
    # the toolbar opens (app.js reads data-sb-moved on Annotate-ON, session-only). Only the WELDED active Done
    # stays non-draggable — the bar's own grip moves that unit, and an independent drag would rip it out of
    # .rail-actions (two positioners over one node). "Welded" = the button is inside the reparented chrome host;
    # the inactive pill is a plain <body> child, so b.closest(host) is null and it drags freely.
    "b.addEventListener('pointerdown',function(e){sc=false;if(e.button!==0)return;"
    "if(b.closest('.pl-scribble-chrome-host'))return;var r=b.getBoundingClientRect();"
    "dg={sx:e.clientX,sy:e.clientY,ox:r.left,oy:r.top,mv:false};try{b.setPointerCapture(e.pointerId);}catch(_){}});"
    "b.addEventListener('pointermove',function(e){if(!dg)return;"
    "if(!dg.mv){if(Math.abs(e.clientX-dg.sx)<4&&Math.abs(e.clientY-dg.sy)<4)return;dg.mv=true;b.dataset.sbMoved='1';b.style.bottom='auto';b.style.right='auto';}"
    "b.style.left=Math.round(Math.max(4,Math.min(window.innerWidth-b.offsetWidth-4,dg.ox+e.clientX-dg.sx)))+'px';"
    "b.style.top=Math.round(Math.max(4,Math.min(window.innerHeight-b.offsetHeight-4,dg.oy+e.clientY-dg.sy)))+'px';});"
    "function ed(){if(dg&&dg.mv)sc=true;dg=null;}"
    "b.addEventListener('pointerup',ed);b.addEventListener('pointercancel',ed);"
    "m();f.addEventListener('load',m);b.addEventListener('click',function(){if(sc){sc=false;return;}on=!on;m();});"
    # RACE-1 (audit blocker): parent-side boot watchdog. Doctrine (CLAUDE.md §11): recovery runs in the realm
    # it was PROVEN in — the parent. Ladder: (1) re-inject the module <script> into the wedged document
    # (field-proven on the live wedge: dynamically-inserted modules are not blocked by pending stylesheets,
    # so this boots with NO reload and no state churn); (2) up to two parent-side srcdoc re-parses (the
    # proven manual recovery; annotate forced off first — the load listener re-syncs m()); (3) fail-INVISIBLE
    # (hide the frame; the inlined anti-FOUC keeps the question readable — never fail-opaque). Stamp reads are
    # fresh each check and fail OPEN (unreadable => booted => no loop). RACE-4: per-load error hook + load
    # counter on the wrap for field forensics (a pre-evaluation module error is otherwise invisible).
    "var sbHeals=0,sbRp=0;"
    "function sbAbsent(){try{return !f.contentWindow||!f.contentWindow.__scribbleBooted;}catch(e){return false;}}"
    "function sbHook(){try{var cw=f.contentWindow;if(cw&&!cw.__sbErrHook){cw.__sbErrHook=1;"
    "cw.addEventListener('error',function(e){try{w.dataset.scribbleErr=String(e.message||e.type).slice(0,120);"
    "console.error('[scribble boot]',e.message||e.type);}catch(_){}});}}catch(e){}}"
    "f.addEventListener('load',function(){w.dataset.scribbleLoads=String((+w.dataset.scribbleLoads||0)+1);sbHook();});"
    "function sbHeal(){try{"
    "if(!sbAbsent())return;"
    "sbHeals++;w.dataset.sbHeals=String(sbHeals);"
    "if(sbHeals===1){var hd=f.contentDocument,mo=hd&&hd.querySelector('script[type=module][src]'),"
    "lk=hd&&hd.querySelector('link[rel=stylesheet]');"
    "if(hd&&mo&&lk&&lk.sheet){var hs=hd.createElement('script');hs.type='module';"
    "hs.src=mo.getAttribute('src');hd.body.appendChild(hs);setTimeout(sbHeal,3000);return;}}"
    "if(sbRp<2){sbRp++;on=false;m();f.setAttribute('srcdoc',f.getAttribute('srcdoc'));"
    "setTimeout(sbHook,300);setTimeout(sbHeal,8000);return;}"
    "on=false;m();b.style.display='none';f.style.visibility='hidden';"
    "}catch(e){if(sbRp<2){setTimeout(sbHeal,8000);}else{try{f.style.visibility='hidden';}catch(_){}}}}"
    "setTimeout(sbHeal,6000);}"
    "})();</script>"
)
# RACE-1 (audit §2.4 item 7): boot watchdog for the NON-overlay frames (Option-B question + read-only
# submission) — the same wedge surface as the overlay, and a wedged READ-ONLY frame silently reads as "the
# student submitted nothing" to a grader. Same parent-realm heal ladder as the overlay sizer, minus annotate
# handling (none exists here). Appended inside each frame's wrap div.
_FRAME_WATCHDOG = (
    "<script>(function(){var fw=document.currentScript.parentElement,"
    "ff=fw.querySelector('.pl-scribble-frame');if(!ff)return;var fh=0,fr=0;"
    "function ab(){try{return !ff.contentWindow||!ff.contentWindow.__scribbleBooted;}catch(e){return false;}}"
    "function hk(){try{var cw=ff.contentWindow;if(cw&&!cw.__sbErrHook){cw.__sbErrHook=1;"
    "cw.addEventListener('error',function(e){try{fw.dataset.scribbleErr=String(e.message||e.type).slice(0,120);"
    "console.error('[scribble boot]',e.message||e.type);}catch(_){}});}}catch(e){}}"
    "ff.addEventListener('load',function(){fw.dataset.scribbleLoads=String((+fw.dataset.scribbleLoads||0)+1);hk();});"
    "function hl(){try{"
    "if(!ab())return;"
    "fh++;fw.dataset.sbHeals=String(fh);"
    "if(fh===1){var hd=ff.contentDocument,mo=hd&&hd.querySelector('script[type=module][src]'),"
    "lk=hd&&hd.querySelector('link[rel=stylesheet]');"
    "if(hd&&mo&&lk&&lk.sheet){var hs=hd.createElement('script');hs.type='module';"
    "hs.src=mo.getAttribute('src');hd.body.appendChild(hs);setTimeout(hl,3000);return;}}"
    "if(fr<2){fr++;ff.setAttribute('srcdoc',ff.getAttribute('srcdoc'));setTimeout(hk,300);setTimeout(hl,8000);return;}"
    "ff.style.visibility='hidden';"
    "}catch(e){if(fr<2){setTimeout(hl,8000);}else{try{ff.style.visibility='hidden';}catch(_){}}}}"
    "setTimeout(hl,6000);})();</script>"
)

_OVERLAY_WRAP = (
    # Full-bleed: negative side margins eat PrairieLearn's 16px card-body padding so Scribble uses the
    # card edge-to-edge (the drawing canvas stays locked at 816px inside, so replay is unaffected).
    '<div class="pl-scribble-wrap pl-scribble-overlay" '
    'style="position:relative;margin:0 -16px;width:calc(100%% + 32px);max-width:none;">'
    "%s"  # hidden form input (question panel) or "" (read-only submission)
    # padding-top clears the single-row merged toolbar; min-height reserves room BELOW the prose for notes.
    '<div class="pl-scribble-host" '
    'style="box-sizing:border-box;min-height:520px;padding:52px 10px 14px;">%s</div>'  # VISIBLE live prose
    "%s"  # the transparent overlay iframe
    "%s"  # the Annotate toggle button (editable) or "" (read-only)
    + _OVERLAY_SIZER
    + "</div>"
)


def _qid(data):
    """A stable per-question id for CLIENT-SIDE layout prefs (panel positions), so a toolbar dragged
    on one question stops restoring on every other question (they all default answers-name).

    Uses the question directory path AFTER the /questions/ segment — nested QIDs (exams/mt1/q3 vs
    exams/mt2/q3) stay distinct where a bare basename would collide — slash-sanitized to dots.
    Falls back to the basename when the marker is absent; None keeps the client on its legacy
    shared key (deploy-order-safe: either artifact can ship first)."""
    p = str(data["options"].get("question_path", "") or "")
    if not p:
        return None
    marker = "/questions/"
    i = p.find(marker)
    rel = p[i + len(marker):] if i >= 0 else os.path.basename(p)
    rel = rel.strip("/").replace("/", ".")
    return rel or None


def _bundle_index(data):
    """Read the deployed Scribble index.html, or None if the bundle isn't there."""
    index_path = os.path.join(data["options"]["client_files_course_path"], "scribble", "index.html")
    try:
        with open(index_path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def _build_srcdoc(doc, base_url, extra_head, overlay=False):
    """Inject <base> + the embed flag + caller head HTML right after <head> (BEFORE the
    CSP meta — load-bearing: inline scripts only run ahead of it; do NOT widen script-src),
    then attribute-escape the whole document for srcdoc=. Returns the escaped srcdoc, or
    None if no <head> was found (tolerates attributes/case on the tag)."""
    flag = "window.__SCRIBBLE_EMBED = true;"
    style = ""
    if overlay:
        # Set the flag AND tag <html class="pl-overlay"> synchronously (this inline script runs before the
        # first paint), so the anti-FOUC CSS can hide the standalone chrome until app.js sets body.overlay.
        # Without it the iframe paints its default standalone look for ~160ms before flipping to the overlay.
        flag += "window.__SCRIBBLE_OVERLAY = true;document.documentElement.classList.add('pl-overlay');"
        # RACE-2 (audit, high): the "invisible until booted" guarantee must NOT ride the style.css network
        # fetch — in the v172 field incident that asset's stall was plausibly the very thing that wedged the
        # boot, so the gate failed exactly when needed and the frame painted OPAQUE over the live question.
        # Inline the two load-bearing rules (duplicated from style.css:658-659 on purpose) so a css-less or
        # module-dead frame degrades to INVISIBLE and click-through (pointer-events:none is parent-side).
        # style-src includes 'unsafe-inline' by design (CLAUDE.md §7), and this sits BEFORE the CSP meta anyway.
        style = ("<style>html.pl-overlay{background:transparent}"
                 "html.pl-overlay body:not(.overlay){visibility:hidden}</style>")
    inject = (
        '<base href="%s"><script>%s</script>%s'
        % (_html.escape(base_url, quote=True), flag, style)
    ) + extra_head
    new_doc, n = re.subn(
        r"<head\b[^>]*>", lambda m: m.group(0) + inject, doc, count=1, flags=re.IGNORECASE
    )
    if n == 0:
        return None
    return _html.escape(new_doc, quote=True)


def prepare(element_html, data):
    element = lxml.html.fragment_fromstring(element_html)
    pl.check_attribs(element, required_attribs=[], optional_attribs=["answers-name", "mode"])


# NOTE: interactive content (inputs, links) MAY be nested inside <pl-scribble mode="overlay">. The drawing
# layer is transparent to pointer events until the student clicks "Annotate" (it flips to capture only while
# drawing, then back on "Done"), so nested widgets render, stay answerable, and grade normally. This lets a
# whole question be wrapped in the element to give it a draw-over-the-question scratchpad.


# Interactive PL widgets whose correct answer belongs in the answer panel — used to decide whether a wrapped
# question has graded content INSIDE <pl-scribble> (pass it through) or not (add nothing, don't leak prose).
_ANSWER_PL = frozenset({
    "pl-multiple-choice", "pl-checkbox", "pl-matching", "pl-order-blocks", "pl-dropdown",
})


def _is_answer_widget(tag):
    return tag in _ANSWER_PL or (tag.startswith("pl-") and tag.endswith("-input"))


def _answer_widget_els(element):
    """The OUTERMOST graded widgets inside <pl-scribble> (skipping any nested inside another widget).

    The answer (correct-answer) panel renders ONLY these — never pl.inner_html — so a wrapped question's
    prose (pl-question-panel, pl-code, etc.) does not get dragged into the correct-answer panel. Widgets
    that live OUTSIDE <pl-scribble> render their own correct answers, so an element with none here adds
    nothing to the answer panel.
    """
    out = []
    for el in element.iterdescendants():
        tag = el.tag.lower() if isinstance(el.tag, str) else ""
        if not _is_answer_widget(tag):
            continue
        anc = el.getparent()
        nested = False
        while anc is not None and anc is not element:
            atag = anc.tag.lower() if isinstance(anc.tag, str) else ""
            if _is_answer_widget(atag):
                nested = True
                break
            anc = anc.getparent()
        if not nested:
            out.append(el)
    return out


def render(element_html, data):
    element = lxml.html.fragment_fromstring(element_html)
    name = pl.get_string_attrib(element, "answers-name", ANSWERS_NAME_DEFAULT)
    mode = pl.get_string_attrib(element, "mode", "inside")
    if mode not in ("inside", "overlay"):
        mode = "inside"  # unknown mode → safe default (Option B)
    overlay = mode == "overlay"
    panel = data["panel"]
    if panel == "answer":
        # The scratchpad has no canonical answer. A WRAPPED question keeps its graded widgets INSIDE the
        # element — render ONLY those widgets (their correct answers), NOT pl.inner_html, which would leak
        # the whole question's prose (pl-question-panel, pl-code, …) into the correct-answer panel. Widgets
        # OUTSIDE <pl-scribble> render their own correct answers, so an element with none adds nothing here.
        widgets = _answer_widget_els(element)
        if not widgets:
            return ""
        return "".join(lxml.html.tostring(w, encoding="unicode") for w in widgets)

    inner = pl.inner_html(element)  # the annotatable content — our element's own children
    base_url = data["options"]["client_files_course_url"].rstrip("/") + "/scribble/"
    doc = _bundle_index(data)
    if doc is None:
        return _MISSING_BUNDLE

    if panel == "submission":
        if overlay:
            # OVERLAY (Option C) graded view: show ONLY the submitted answers — never the annotation. The
            # strokes are saved in page coords relative to the WHOLE live question; but in the submission panel
            # the prose (pl-question-panel/pl-code) is hidden, so replaying them would float the drawing,
            # misaligned, in blank space (the confusing "scribble on nothing" the student saw). Showing it
            # aligned would require re-drawing the whole question, which we deliberately don't. The drawing
            # stays saved for the STUDENT's own continued work (the question panel re-seeds it); the graded
            # panel just surfaces the nested graded widgets' submitted answers (+ correct/incorrect badges).
            # Widgets OUTSIDE <pl-scribble> render their own submissions, so an element with none adds nothing.
            widgets = _answer_widget_els(element)
            return "".join(lxml.html.tostring(w, encoding="unicode") for w in widgets) if widgets else ""
        # Option B (non-overlay embed): the annotation replays in a SELF-CONTAINED clone of the question, so it
        # stays aligned — keep showing it read-only. No annotations → contribute nothing (widgets render their
        # own submissions).
        blob = data["submitted_answers"].get(name) or ""
        if not blob:
            return ""
        # SEC-1 (audit): \u003c-escape the JSON before inlining — a "</script>" inside any field (e.g. a
        # student blob surfaced under an answers-name collision) would otherwise close this tag and execute
        # in the PL origin when STAFF view the panel. \u003c is transparent to JSON.parse.
        cfg = "<script>window.__SCRIBBLE_PL=%s;window.__SCRIBBLE_READONLY=true;</script>" % json.dumps(
            {"readOnly": True, "data": blob, "name": name, "qid": _qid(data)}  # same namespaced PREFS_KEY as the editable view
        ).replace("<", "\\u003c")
        srcdoc = _build_srcdoc(doc, base_url, cfg, overlay=False)
        if srcdoc is None:
            return _INJECT_FAIL
        return (
            '<div class="pl-scribble-wrap" style="margin:14px 0;">'
            '<div class="pl-scribble-source" hidden>%s</div>%s'
            + _FRAME_WATCHDOG + "</div>"
        ) % (inner, _FRAME % ("Saved annotations", srcdoc))

    # panel == "question": editable, with a hidden form input PrairieLearn persists.
    # SEC-1: same \u003c hardening as the read-only panel (qid/name are course-authored, but the rule is uniform).
    qid = _qid(data)  # v189: compute once — reused for cfg below and the overlay launcher sid
    cfg = "<script>window.__SCRIBBLE_PL=%s;</script>" % json.dumps(
        {"readOnly": False, "name": name, "qid": qid}).replace("<", "\\u003c")
    srcdoc = _build_srcdoc(doc, base_url, cfg, overlay=overlay)
    if srcdoc is None:
        return _INJECT_FAIL
    prior = data["submitted_answers"].get(name)  # seed the prior submission so the student continues
    seed = prior if isinstance(prior, str) else ""
    input_html = '<input type="hidden" class="pl-scribble-input" name="%s" value="%s">' % (
        _html.escape(name, quote=True),
        _html.escape(seed, quote=True),
    )
    if overlay:
        # Live question visible; transparent Scribble iframe over it. Answer widgets may live INSIDE or
        # OUTSIDE <pl-scribble>: the overlay only captures pointer events while the student is drawing, so
        # nested inputs stay answerable (verified end-to-end: render + type-through + grade).
        # v177 A3: identity-stamp the launcher so app.js's weld binds by id, never by first-match (B3-3).
        sid = _html.escape("%s.%s" % (qid or "q", name), quote=True)
        return _OVERLAY_WRAP % (input_html, inner, _OVERLAY_FRAME % ("Scribble scratchpad", srcdoc), _ANNOTATE_BTN % sid)
    return (
        '<div class="pl-scribble-wrap" style="margin:14px 0;">'
        '<div class="pl-scribble-source" hidden>%s</div>'
        "%s%s" + _FRAME_WATCHDOG + "</div>"
    ) % (inner, input_html, _FRAME % ("Scribble scratchpad", srcdoc))


def parse(element_html, data):
    """Size-cap, reject non-finite/oversize/malformed payloads, and canonicalize the submitted annotations.

    This is NOT full schema validation — the authoritative Scribble document validator is the Rust
    load_json(), which runs client-side in the iframe on every render (and rejects unknown fields, bad
    enums, caps, non-finite coords, etc.). parse() only bounds size/shape and strips non-finite literals
    so PrairieLearn never stores a blob that (a) breaks the client JSON.parse or (b) exhausts the worker.
    Any FUTURE server-side consumer (grading, export) MUST re-run the Rust validator before trusting it.
    """
    element = lxml.html.fragment_fromstring(element_html)
    name = pl.get_string_attrib(element, "answers-name", ANSWERS_NAME_DEFAULT)
    raw = data["submitted_answers"].get(name)
    if not raw:  # None or "" — a blank scratchpad is valid (nothing saved)
        data["submitted_answers"][name] = None
        return
    if not isinstance(raw, str) or len(raw) > MAX_B64:
        data["submitted_answers"][name] = None
        data["format_errors"][name] = "Saved annotations are too large."
        return
    try:
        decoded = base64.b64decode(raw, validate=True)
        if len(decoded) > MAX_ANNOTATION_BYTES:
            raise ValueError("too large")
        # parse_constant rejects Infinity/-Infinity/NaN before they can be re-emitted (S1).
        obj = json.loads(decoded.decode("utf-8"), parse_constant=_reject_constant)
        if not isinstance(obj, dict):  # weak shape gate; Rust load_json is authoritative client-side
            raise ValueError("bad shape")
        _within_structural_bounds(obj)  # bound node count + depth (B2)
        # allow_nan=False is belt-and-suspenders: any residual non-finite float would raise here too.
        canon = json.dumps(obj, separators=(",", ":"), allow_nan=False).encode("utf-8")
        data["submitted_answers"][name] = base64.b64encode(canon).decode("ascii")
    except Exception:
        data["submitted_answers"][name] = None
        data["format_errors"][name] = "Could not read saved annotations."
