"""pl-scribble — embed the Scribble annotation tool in a PrairieLearn question.

The annotatable content is THIS element's own children (encapsulation: Scribble never
traverses PL's surrounding DOM). render() emits it as a hidden .pl-scribble-source inside
our .pl-scribble-wrap; embed.js clones it from frameElement.parentElement (our own output).

Persistence: the student's annotations are serialized (base64 of save_json()) into a hidden
<input> inside our wrapper — which sits in PL's <form> — so PrairieLearn saves them on Save /
Save & Grade like any answer. parse() validates the round-tripped blob; the submission panel
re-renders it read-only (window.__SCRIBBLE_READONLY).

Why a srcdoc iframe (not <iframe src=...>): PrairieLearn stamps
`Content-Security-Policy: frame-ancestors 'none'` + `X-Frame-Options: DENY` on every text/html
response, which blocks framing a served index.html — even same-origin. A `srcdoc` iframe is
generated by the parent document (no PL HTTP response carries those headers), so the framing
block never applies. A non-sandboxed srcdoc iframe is same-origin with the parent, and a
`<base href>` makes every relative asset URL resolve to clientFilesCourse/scribble/.

Deploy the COMPILED Scribble bundle to [course]/clientFilesCourse/scribble/ (see prairielearn/deploy.sh).
"""

import base64
import html as _html
import json
import os
import re

import lxml.html
import prairielearn as pl

ANSWERS_NAME_DEFAULT = "scribble"
MAX_JSON_BYTES = 30 * 1024 * 1024  # mirror scribble/src/model.rs MAX_JSON_BYTES (cap on DECODED bytes)
MAX_B64 = (MAX_JSON_BYTES + 2) // 3 * 4 + 16  # base64-inflated pre-filter on the raw input

_MISSING_BUNDLE = (
    '<div style="padding:12px;border:1px solid #f0d9a8;background:#fff7e6;border-radius:8px;">'
    "<strong>pl-scribble:</strong> the Scribble bundle was not found at "
    "<code>clientFilesCourse/scribble/index.html</code>. Build it and run "
    "<code>prairielearn/deploy.sh</code>.</div>"
)
_INJECT_FAIL = (
    '<div style="padding:12px;border:1px solid #f0d9a8;background:#fff7e6;border-radius:8px;">'
    "<strong>pl-scribble:</strong> could not inject the asset base — no &lt;head&gt; found in "
    "the Scribble bundle. The bundle may be malformed.</div>"
)
_FRAME = (
    '<iframe class="pl-scribble-frame" title="%s" '
    'style="width:100%%;height:660px;border:1px solid #d7dbe0;border-radius:10px;display:block;" '
    'srcdoc="%s"></iframe>'
)
# Option C (overlay): the question prose renders VISIBLY in .pl-scribble-host and a TRANSPARENT
# Scribble iframe is laid over it so the student draws on the LIVE question rather than a clone.
# width:100% fills the host; HEIGHT is set by _OVERLAY_SIZER (an iframe is a REPLACED element —
# absolute inset:0 does NOT stretch it, so we size it to the prose in JS). The page coords are
# locked to HTML_BASE_W=816 inside Scribble so the fixed-width replay in hydrateAnnotations stays
# faithful; min-height (== Scribble's 200px page floor) stops a short prose from clipping the canvas.
_OVERLAY_FRAME = (
    '<iframe class="pl-scribble-overlay-frame" title="%s" '
    'style="position:absolute;top:0;left:0;width:100%%;height:200px;border:0;background:transparent;" '
    'srcdoc="%s"></iframe>'
)
# Size the overlay iframe to the live prose host (and keep it in sync on load / MathJax / resize).
# A custom element may emit a parent-page inline <script>; PrairieLearn's page CSP has no script-src.
_OVERLAY_SIZER = (
    "<script>(function(){var w=document.currentScript.parentElement,"
    "h=w.querySelector('.pl-scribble-host'),f=w.querySelector('.pl-scribble-overlay-frame');"
    "function s(){f.style.height=Math.max(h.offsetHeight,200)+'px';}s();"
    "window.addEventListener('load',s);window.addEventListener('resize',s);"
    "if(window.MathJax&&MathJax.startup&&MathJax.startup.promise){MathJax.startup.promise.then(s);}"
    "})();</script>"
)
_OVERLAY_WRAP = (
    '<div class="pl-scribble-wrap pl-scribble-overlay" '
    'style="position:relative;margin:14px 0;width:816px;max-width:100%%;">'
    "%s"  # hidden form input (question panel) or "" (read-only submission)
    # padding-top clears the floating toolbar band; min-height gives room to sketch below the
    # prose. box-sizing:border-box so the height math matches Scribble's measured offsetHeight.
    '<div class="pl-scribble-host" '
    # padding-top clears the SINGLE-row merged toolbar; the tall min-height reserves room BELOW the
    # prose for the docked notes panel (opened by default in overlay mode).
    'style="box-sizing:border-box;min-height:520px;padding:60px 10px 14px;">%s</div>'  # VISIBLE live prose
    "%s"  # the transparent overlay iframe
    + _OVERLAY_SIZER
    + "</div>"
)


def _bundle_index(data):
    """Read the deployed Scribble index.html, or None if the bundle isn't there."""
    index_path = os.path.join(data["options"]["client_files_course_path"], "scribble", "index.html")
    try:
        with open(index_path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def _build_srcdoc(doc, base_url, extra_head, overlay=False):
    """Inject <base> + the embed flag + caller head HTML right after <head> (BEFORE the
    CSP meta — load-bearing: inline scripts only run ahead of it; do NOT widen script-src),
    then attribute-escape the whole document for srcdoc=. Returns the escaped srcdoc, or
    None if no <head> was found (tolerates attributes/case on the tag)."""
    flag = "window.__SCRIBBLE_EMBED = true;"
    if overlay:
        flag += "window.__SCRIBBLE_OVERLAY = true;"  # Option C: transparent draw-over-live-question
    inject = (
        '<base href="%s"><script>%s</script>'
        % (_html.escape(base_url, quote=True), flag)
    ) + extra_head
    new_doc, n = re.subn(
        r"<head\b[^>]*>", lambda m: m.group(0) + inject, doc, count=1, flags=re.IGNORECASE
    )
    if n == 0:
        return None
    return _html.escape(new_doc, quote=True)


def prepare(element_html, data):
    element = lxml.html.fragment_fromstring(element_html)
    pl.check_attribs(element, required_attribs=[], optional_attribs=["answers-name", "mode"])


def render(element_html, data):
    element = lxml.html.fragment_fromstring(element_html)
    name = pl.get_string_attrib(element, "answers-name", ANSWERS_NAME_DEFAULT)
    mode = pl.get_string_attrib(element, "mode", "inside")
    if mode not in ("inside", "overlay"):
        mode = "inside"  # unknown mode → safe default (Option B)
    overlay = mode == "overlay"
    panel = data["panel"]
    if panel == "answer":
        return ""  # a scratchpad has no canonical answer to show

    inner = pl.inner_html(element)  # the annotatable content — our element's own children
    base_url = data["options"]["client_files_course_url"].rstrip("/") + "/scribble/"
    doc = _bundle_index(data)
    if doc is None:
        return _MISSING_BUNDLE

    if panel == "submission":
        # A saved submission: render the annotations read-only, injected server-side.
        blob = data["submitted_answers"].get(name) or ""
        if not blob:
            return '<div class="pl-scribble-wrap" style="margin:14px 0;"><em>No saved annotations.</em></div>'
        # blob is base64 (alphabet has no <, >, ") → safe inside a JS string and an HTML attr.
        cfg = "<script>window.__SCRIBBLE_PL=%s;window.__SCRIBBLE_READONLY=true;</script>" % json.dumps(
            {"readOnly": True, "data": blob}
        )
        srcdoc = _build_srcdoc(doc, base_url, cfg, overlay=overlay)
        if srcdoc is None:
            return _INJECT_FAIL
        if overlay:
            # Re-render the live question; the saved strokes replay over it, read-only.
            return _OVERLAY_WRAP % ("", inner, _OVERLAY_FRAME % ("Saved annotations", srcdoc))
        return (
            '<div class="pl-scribble-wrap" style="margin:14px 0;">'
            '<div class="pl-scribble-source" hidden>%s</div>%s</div>'
        ) % (inner, _FRAME % ("Saved annotations", srcdoc))

    # panel == "question": editable, with a hidden form input PrairieLearn persists.
    cfg = "<script>window.__SCRIBBLE_PL=%s;</script>" % json.dumps({"readOnly": False, "name": name})
    srcdoc = _build_srcdoc(doc, base_url, cfg, overlay=overlay)
    if srcdoc is None:
        return _INJECT_FAIL
    prior = data["submitted_answers"].get(name)  # seed the prior submission so the student continues
    seed = prior if isinstance(prior, str) else ""
    input_html = '<input type="hidden" class="pl-scribble-input" name="%s" value="%s">' % (
        _html.escape(name, quote=True),
        _html.escape(seed, quote=True),
    )
    if overlay:
        # Live question visible; transparent Scribble iframe over it. Answer widgets live
        # OUTSIDE <pl-scribble> so the pointer-capturing overlay never covers an input.
        return _OVERLAY_WRAP % (input_html, inner, _OVERLAY_FRAME % ("Scribble scratchpad", srcdoc))
    return (
        '<div class="pl-scribble-wrap" style="margin:14px 0;">'
        '<div class="pl-scribble-source" hidden>%s</div>'
        "%s%s</div>"
    ) % (inner, input_html, _FRAME % ("Scribble scratchpad", srcdoc))


def parse(element_html, data):
    """Validate + canonicalize the submitted annotations server-side before grading/re-render
    (the authoritative Rust validation otherwise only runs client-side in the iframe)."""
    element = lxml.html.fragment_fromstring(element_html)
    name = pl.get_string_attrib(element, "answers-name", ANSWERS_NAME_DEFAULT)
    raw = data["submitted_answers"].get(name)
    if not raw:  # None or "" — a blank scratchpad is valid (nothing saved)
        data["submitted_answers"][name] = None
        return
    if not isinstance(raw, str) or len(raw) > MAX_B64:
        data["submitted_answers"][name] = None
        data["format_errors"][name] = "Saved annotations are too large."
        return
    try:
        decoded = base64.b64decode(raw, validate=True)
        if len(decoded) > MAX_JSON_BYTES:
            raise ValueError("too large")
        obj = json.loads(decoded.decode("utf-8"))
        if not isinstance(obj, dict):  # weak shape gate; Rust load_json is authoritative client-side
            raise ValueError("bad shape")
        canon = json.dumps(obj, separators=(",", ":")).encode("utf-8")
        data["submitted_answers"][name] = base64.b64encode(canon).decode("ascii")
    except Exception:
        data["submitted_answers"][name] = None
        data["format_errors"][name] = "Could not read saved annotations."
